version: 'Docker version 27.5.1, build 9f9e405'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    container_name: teslo_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
